import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: ["class"],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        parchment: "#f5f4ed",
        ivory: "#faf9f5",
        "warm-sand": "#e8e6dc",
        "warm-silver": "#b0aea5",
        "charcoal-warm": "#4d4c48",
        "olive-gray": "#5e5d59",
        "stone-gray": "#87867f",
        "dark-warm": "#3d3d3a",
        "dark-surface": "#30302e",
        "near-black": "#141413",
        "border-cream": "#f0eee6",
        "border-warm": "#e8e6dc",
        "ring-warm": "#d1cfc5",
        "ring-deep": "#c2c0b6",
        terracotta: {
          DEFAULT: "#c96442",
          soft: "#d97757",
        },
        "error-crimson": "#b53333",
        "focus-blue": "#3898ec",
        // Landing / app shell palette (light parchment).
        bg: "#faf6ef",
        "bg-2": "#faf9f5",
        card: "#ffffff",
        "card-2": "#faf9f5",
        text: "#1f1a14",
        "text-2": "#5e5d59",
        "text-3": "#87867f",
        "text-muted": "rgba(31,26,20,0.6)",
        accent: "#b97340",
        "accent-2": "#d8a373",
        "accent-soft": "rgba(185,115,64,0.12)",
        border: "rgba(0,0,0,0.06)",
        "border-strong": "rgba(0,0,0,0.10)",
        // "مكتبة عِلم" parchment design palette (additive, var-backed). Used by
        // the landing components and the reskinned shared navbar. New names so
        // they never collide with the app-wide tokens above.
        paper: "var(--paper)",
        "paper-card": "var(--paper-card)",
        "paper-soft": "var(--paper-soft)",
        "paper-line": "var(--paper-line)",
        "ink-deep": "var(--ink-deep)",
        "ink-warm": "var(--ink-warm)",
        "ink-mute": "var(--ink-mute)",
        gold: "var(--gold)",
        "gold-soft": "var(--gold-soft)",
        "gold-line": "var(--gold-line)",
        "green-deep": "var(--green-deep)",
        maroon: "var(--maroon)",
      },
      fontFamily: {
        serif: [
          "var(--font-serif)",
          "var(--font-arabic)",
          "Georgia",
          "serif",
        ],
        sans: [
          "var(--font-arabic)",
          "var(--font-manrope)",
          "system-ui",
          "sans-serif",
        ],
        mono: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
        arabic: ["var(--font-arabic)", "system-ui", "sans-serif"],
        fraunces: ["var(--font-fraunces)", "Georgia", "serif"],
        amiri: ["var(--font-amiri)", "var(--font-arabic)", "serif"],
        geist: ["var(--font-inter)", "var(--font-manrope)", "system-ui", "sans-serif"],
        "display-ar": [
          "var(--font-display-ar)",
          "var(--font-amiri)",
          "Amiri",
          "Noto Naskh Arabic",
          "serif",
        ],
        "body-ar": [
          "var(--font-body-ar)",
          "Readex Pro",
          "var(--font-arabic)",
          "system-ui",
          "sans-serif",
        ],
        readex: [
          "var(--font-readex)",
          "var(--font-body-ar)",
          "var(--font-arabic)",
          "system-ui",
          "sans-serif",
        ],
        inter: ["var(--font-inter)", "system-ui", "sans-serif"],
        "reem-kufi": [
          "var(--font-reem-kufi)",
          "var(--font-arabic)",
          "var(--font-amiri)",
          "system-ui",
          "sans-serif",
        ],
      },
      keyframes: {
        "cursor-blink": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "live-dot": {
          "0%, 100%": { transform: "scale(1)", opacity: "1" },
          "50%": { transform: "scale(1.35)", opacity: "0.55" },
        },
      },
      animation: {
        "cursor-blink": "cursor-blink 1.1s ease-in-out infinite",
        "live-dot": "live-dot 2s ease-in-out infinite",
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "8px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "24px",
        "3xl": "32px",
      },
      boxShadow: {
        "ring-warm": "0 0 0 1px #d1cfc5",
        "ring-deep": "0 0 0 1px #c2c0b6",
        "ring-cream": "0 0 0 1px #f0eee6",
        whisper: "0 4px 24px rgba(0,0,0,0.05)",
        "hero-search":
          "0 1px 2px rgba(0,0,0,0.04), 0 12px 32px rgba(120,80,40,0.08)",
        "hero-search-hover":
          "0 1px 2px rgba(0,0,0,0.05), 0 18px 42px rgba(120,80,40,0.12)",
      },
    },
  },
  plugins: [],
};
export default config;
