# Generated by Django 5.2.15 on 2026-07-11 08:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search_engine', '0025_alter_chatmessage_citations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocumentAffinity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_count', models.PositiveIntegerField(default=0)),
                ('total_read_ms', models.BigIntegerField(default=0)),
                ('pages_read', models.PositiveIntegerField(default=0)),
                ('in_doc_search_count', models.PositiveIntegerField(default=0)),
                ('assistant_query_count', models.PositiveIntegerField(default=0)),
                ('bookmark_count', models.PositiveIntegerField(default=0)),
                ('note_count', models.PositiveIntegerField(default=0)),
                ('highlight_count', models.PositiveIntegerField(default=0)),
                ('percent_complete', models.FloatField(default=0.0)),
                ('engagement_score', models.FloatField(db_index=True, default=0.0)),
                ('first_engaged_at', models.DateTimeField(blank=True, null=True)),
                ('last_engaged_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_affinities', to='search_engine.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_affinities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User-Document Affinity',
                'verbose_name_plural': 'User-Document Affinities',
                'db_table': 'analytics_user_document_affinity',
                'indexes': [models.Index(fields=['user', '-engagement_score'], name='analytics_u_user_id_ffd061_idx'), models.Index(fields=['user', '-last_engaged_at'], name='analytics_u_user_id_ae02e4_idx')],
                'unique_together': {('user', 'document')},
            },
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('document_open', 'Document opened'), ('reading_session', 'Reading session'), ('search', 'Corpus search'), ('search_assist', 'NL search assist'), ('in_doc_search', 'In-document search'), ('suggestion_select', 'Suggestion selected'), ('assistant_query', 'Assistant question'), ('bookmark_add', 'Bookmark added'), ('bookmark_remove', 'Bookmark removed'), ('note_add', 'Note added'), ('highlight_add', 'Highlight added'), ('filter_apply', 'Filter applied'), ('preset_apply', 'Preset applied')], db_index=True, max_length=32)),
                ('session_id', models.CharField(blank=True, default='', help_text='Client browsing-session id (sessionization); blank for server events.', max_length=64)),
                ('source', models.CharField(blank=True, default='web', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Event payload: query text, mode, filters, duration_ms, result_count, …')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='search_engine.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Event',
                'verbose_name_plural': 'User Events',
                'db_table': 'analytics_user_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_u_user_id_0c1e19_idx'), models.Index(fields=['document', 'event_type'], name='analytics_u_documen_27660e_idx'), models.Index(fields=['event_type', '-created_at'], name='analytics_u_event_t_66ba6b_idx')],
            },
        ),
    ]
