# Generated by Django 5.2.16 on 2026-07-25 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search_engine', '0028_document_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(blank=True, choices=[('fiqh', 'فقه'), ('usul_fiqh', 'أصول الفقه'), ('hadith', 'حديث'), ('tafsir', 'تفسير'), ('ulum_quran', 'علوم القرآن'), ('aqida', 'عقيدة'), ('sira', 'سيرة'), ('tarikh', 'تاريخ'), ('tarajim', 'تراجم وطبقات'), ('adab', 'أدب'), ('lugha', 'لغة ونحو وصرف'), ('tasawwuf', 'تصوف وسلوك'), ('tibb', 'طب'), ('falsafa_mantiq', 'فلسفة ومنطق'), ('fatawa', 'فتاوى'), ('ansab', 'أنساب'), ('jughrafiya', 'جغرافيا ورحلات'), ('other', 'أخرى')], db_index=True, default='', max_length=30)),
                ('genres_secondary', models.JSONField(blank=True, default=list)),
                ('genre_confidence', models.FloatField(blank=True, null=True)),
                ('madhhab', models.CharField(blank=True, choices=[('hanafi', 'حنفي'), ('maliki', 'مالكي'), ('shafii', 'شافعي'), ('hanbali', 'حنبلي'), ('zahiri', 'ظاهري'), ('jafari', 'جعفري'), ('zaydi', 'زيدي'), ('ibadi', 'إباضي'), ('multi', 'مقارن/متعدد'), ('na', 'لا ينطبق'), ('unknown', 'غير محدد')], db_index=True, default='', max_length=20)),
                ('madhhab_confidence', models.FloatField(blank=True, null=True)),
                ('era_century', models.IntegerField(blank=True, db_index=True, help_text='Hijri century of COMPOSITION (distinct from author death century)', null=True)),
                ('era_confidence', models.FloatField(blank=True, null=True)),
                ('register', models.CharField(blank=True, choices=[('classical', 'فصحى تراثية'), ('modern', 'فصحى حديثة'), ('mixed', 'مختلط'), ('non_arabic', 'غير عربي')], default='', max_length=20)),
                ('register_confidence', models.FloatField(blank=True, null=True)),
                ('physical_class', models.CharField(blank=True, choices=[('printed_book', 'كتاب مطبوع'), ('newspaper', 'صحيفة/مجلة'), ('manuscript_scan', 'مخطوط'), ('thesis', 'رسالة جامعية'), ('other', 'أخرى')], db_index=True, default='', max_length=20)),
                ('physical_confidence', models.FloatField(blank=True, null=True)),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='field → short verbatim quote justifying it')),
                ('extractor_version', models.CharField(default='', max_length=20)),
                ('model_id', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=10)),
                ('degraded_reason', models.TextField(blank=True, default='', help_text='Loud failure surface — a dead OPENROUTER_API_KEY must never fail silently')),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('human_verified', models.BooleanField(db_index=True, default=False, help_text='Verified classifications are never overwritten by LLM re-runs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_meta', to='search_engine.document')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document metadata',
                'verbose_name_plural': 'Document metadata',
                'db_table': 'extraction_document_meta',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('ism', models.CharField(blank=True, default='', max_length=100)),
                ('kunya', models.CharField(blank=True, default='', max_length=100)),
                ('nasab', models.CharField(blank=True, default='', max_length=255)),
                ('nisba', models.CharField(blank=True, default='', max_length=100)),
                ('laqab', models.CharField(blank=True, default='', max_length=100)),
                ('shuhra', models.CharField(blank=True, default='', max_length=150)),
                ('honorific_class', models.CharField(blank=True, default='', help_text="Status signal from honorifics: 'prophet', 'sahabi', '' …", max_length=30)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('blocking_key', models.CharField(db_index=True, help_text='Normalized shuhra/kunya/ism — groups candidate duplicates', max_length=150)),
                ('death_date_raw', models.CharField(blank=True, default='', max_length=100)),
                ('death_year_hijri', models.IntegerField(blank=True, null=True)),
                ('death_century', models.IntegerField(blank=True, db_index=True, null=True)),
                ('wikidata_id', models.CharField(blank=True, default='', max_length=32)),
                ('viaf_id', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(choices=[('extracted', 'Extracted'), ('author_import', 'Author import'), ('manual', 'Manual')], max_length=20)),
                ('review_status', models.CharField(db_index=True, default='pending', max_length=10)),
                ('mention_doc_count', models.PositiveIntegerField(default=0, help_text='Denormalized distinct-document mention count (typeahead ordering)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='persons', to='search_engine.author')),
            ],
            options={
                'db_table': 'extraction_persons',
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_translit', models.CharField(blank=True, default='', max_length=255)),
                ('modern_name', models.CharField(blank=True, default='', max_length=255)),
                ('feature_type', models.CharField(blank=True, default='', max_length=30)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source', models.CharField(choices=[('thurayya', 'al-Thurayya'), ('geonames', 'GeoNames'), ('manual', 'Manual')], max_length=20)),
                ('source_id', models.CharField(max_length=64)),
                ('wikidata_id', models.CharField(blank=True, default='', max_length=32)),
                ('mention_doc_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'extraction_places',
                'unique_together': {('source', 'source_id')},
            },
        ),
        migrations.CreateModel(
            name='EntityMention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('char_start', models.PositiveIntegerField()),
                ('char_end', models.PositiveIntegerField()),
                ('surface_text', models.TextField()),
                ('normalized_text', models.CharField(db_index=True, help_text="Grouping key: 'quran:2:255', 'bukhari:52', 'hijri:728', a person blocking key, a place normalized name…", max_length=255)),
                ('normalized', models.JSONField(blank=True, default=dict)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('place', 'Place'), ('date', 'Date'), ('quran', 'Quran citation'), ('hadith_source', 'Hadith takhrij')], max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('extractor_name', models.CharField(max_length=50)),
                ('extractor_version', models.CharField(max_length=20)),
                ('content_hash', models.CharField(help_text='sha256 of the page content at extraction time', max_length=64)),
                ('review_status', models.CharField(choices=[('auto', 'Auto (high confidence)'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('orphaned', 'Orphaned (page changed)')], db_index=True, default='auto', max_length=10)),
                ('human_verified', models.BooleanField(default=False)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_mentions', to='search_engine.document')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='extraction.person')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='extraction.place')),
            ],
            options={
                'db_table': 'extraction_entity_mentions',
            },
        ),
        migrations.CreateModel(
            name='PlaceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized', models.CharField(db_index=True, max_length=255)),
                ('kind', models.CharField(choices=[('primary', 'Primary'), ('variant', 'Variant'), ('historical', 'Historical'), ('nisba', 'Nisba')], max_length=12)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='extraction.place')),
            ],
            options={
                'db_table': 'extraction_place_names',
            },
        ),
        migrations.CreateModel(
            name='ExtractionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extractor_name', models.CharField(max_length=50)),
                ('extractor_version', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('corpus_hash', models.CharField(blank=True, default='', help_text='sha256 over the ordered page hashes at extraction time — unchanged hash ⇒ re-run is a no-op', max_length=64)),
                ('mention_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_runs', to='search_engine.document')),
            ],
            options={
                'db_table': 'extraction_runs',
                'indexes': [models.Index(fields=['extractor_name', 'status'], name='extraction__extract_3ecf5a_idx')],
                'unique_together': {('document', 'extractor_name', 'extractor_version')},
            },
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['-mention_doc_count'], name='extraction__mention_e96d20_idx'),
        ),
        migrations.AddIndex(
            model_name='entitymention',
            index=models.Index(condition=models.Q(('superseded_at__isnull', True)), fields=['document', 'page_number'], name='mention_active_page_idx'),
        ),
        migrations.AddIndex(
            model_name='entitymention',
            index=models.Index(condition=models.Q(('superseded_at__isnull', True)), fields=['entity_type', 'normalized_text'], name='mention_active_key_idx'),
        ),
        migrations.AddIndex(
            model_name='entitymention',
            index=models.Index(fields=['review_status', 'confidence'], name='extraction__review__c2670b_idx'),
        ),
        migrations.AddConstraint(
            model_name='entitymention',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gt', models.F('char_start'))), name='mention_span_valid'),
        ),
        migrations.AddConstraint(
            model_name='entitymention',
            constraint=models.UniqueConstraint(fields=('document', 'extractor_name', 'extractor_version', 'entity_type', 'page_number', 'char_start', 'char_end'), name='mention_unique_per_version'),
        ),
        migrations.AlterUniqueTogether(
            name='placename',
            unique_together={('place', 'normalized', 'kind')},
        ),
    ]
