# Generated by Django 5.2.16 on 2026-07-27 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extraction', '0001_initial'),
        ('search_engine', '0028_document_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitymention',
            name='entity_type',
            field=models.CharField(choices=[('person', 'Person'), ('place', 'Place'), ('date', 'Date'), ('quran', 'Quran citation'), ('hadith_source', 'Hadith takhrij'), ('organization', 'Organization'), ('work_title', 'Work title'), ('event', 'Event'), ('money', 'Money'), ('measure', 'Measure'), ('percent', 'Percent'), ('law_regulation', 'Law / regulation'), ('product_brand', 'Product / brand'), ('id_number', 'Identifier'), ('isnad', 'Isnad chain span'), ('matn', 'Matn span'), ('poetry', 'Poetry span'), ('quote', 'Quotation span')], max_length=20),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_title', models.CharField(max_length=255)),
                ('normalized_title', models.CharField(db_index=True, max_length=255)),
                ('wikidata_id', models.CharField(blank=True, default='', max_length=32)),
                ('openiti_id', models.CharField(blank=True, default='', max_length=64)),
                ('shamela_id', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(choices=[('extracted', 'Extracted'), ('library_import', 'Library import'), ('manual', 'Manual')], max_length=20)),
                ('review_status', models.CharField(db_index=True, default='pending', max_length=10)),
                ('mention_doc_count', models.PositiveIntegerField(default=0, help_text='Denormalized distinct-document mention count (typeahead ordering)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='extraction.person')),
                ('document', models.ForeignKey(blank=True, help_text="The library's own copy of this work, when we hold one", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canonical_works', to='search_engine.document')),
            ],
            options={
                'db_table': 'extraction_works',
            },
        ),
        migrations.CreateModel(
            name='EntityRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.CharField(choices=[('taught', 'Teacher of'), ('transmitted_to', 'Isnad edge'), ('parent_of', 'Parent of'), ('spouse_of', 'Spouse of'), ('sibling_of', 'Sibling of'), ('kin_of', 'Kin of'), ('authored', 'Authored'), ('commentary_on', 'شرح على'), ('gloss_on', 'حاشية على'), ('abridgment_of', 'مختصر لـ'), ('refutation_of', 'رد على'), ('versification_of', 'نظم لـ'), ('takhrij_of', 'تخريج لـ'), ('cites', 'Cites'), ('born_in', 'Born in'), ('died_in', 'Died in'), ('resided_in', 'Resided in'), ('traveled_to', 'Traveled to'), ('held_office', 'Held office'), ('adheres_to', 'Madhhab of'), ('born_on', 'Born on'), ('died_on', 'Died on'), ('dated_event', 'Dated event'), ('attributed_to', 'Spoken by')], db_index=True, max_length=20)),
                ('subject_text', models.CharField(blank=True, default='', max_length=255)),
                ('object_text', models.CharField(blank=True, default='', max_length=255)),
                ('qualifiers', models.JSONField(blank=True, default=dict)),
                ('page_number', models.PositiveIntegerField()),
                ('char_start', models.PositiveIntegerField()),
                ('char_end', models.PositiveIntegerField()),
                ('evidence_text', models.TextField()),
                ('content_hash', models.CharField(help_text='sha256 of the page content at extraction time', max_length=64)),
                ('confidence', models.FloatField(default=1.0)),
                ('extractor_name', models.CharField(max_length=50)),
                ('extractor_version', models.CharField(max_length=20)),
                ('dedupe_key', models.CharField(help_text='sha256(predicate|subject key|object key|page|start|end) — free-text tails keep multi-column uniqueness impractical', max_length=64)),
                ('review_status', models.CharField(choices=[('auto', 'Auto (high confidence)'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('orphaned', 'Orphaned (page changed)')], db_index=True, default='auto', max_length=10)),
                ('human_verified', models.BooleanField(default=False)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_relations', to='search_engine.document')),
                ('object_mention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_as_object', to='extraction.entitymention')),
                ('object_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='extraction.person')),
                ('object_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='extraction.place')),
                ('subject_mention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations_as_subject', to='extraction.entitymention')),
                ('subject_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='extraction.person')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('object_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='extraction.work')),
            ],
            options={
                'db_table': 'extraction_entity_relations',
            },
        ),
        migrations.AddField(
            model_name='entitymention',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentions', to='extraction.work'),
        ),
        migrations.CreateModel(
            name='WorkName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('normalized', models.CharField(db_index=True, max_length=255)),
                ('kind', models.CharField(choices=[('primary', 'Primary'), ('variant', 'Variant'), ('short', 'Short title')], max_length=12)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='extraction.work')),
            ],
            options={
                'db_table': 'extraction_work_names',
            },
        ),
        migrations.CreateModel(
            name='DocumentStructuredExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('paper_meta', 'Academic front matter'), ('references', 'Structured references'), ('captions', 'Figure/table captions'), ('masthead', 'Press masthead'), ('articles', 'Press article units'), ('ads', 'Advertisement segments'), ('obituaries', 'Obituary units'), ('colophon', 'Manuscript colophon'), ('codicology', 'Ownership/waqf/samaat/shelfmark/marginalia'), ('archival_deed', 'Deed: parties/witnesses/qadi/boundaries'), ('fatwa_units', 'Fatwa question/answer units')], db_index=True, max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('page_refs', models.JSONField(blank=True, default=list, help_text="[{'page_number', 'char_start', 'char_end'}] best-effort anchors")),
                ('confidence', models.FloatField(default=1.0)),
                ('extractor_name', models.CharField(max_length=50)),
                ('extractor_version', models.CharField(max_length=20)),
                ('model_id', models.CharField(blank=True, default='', max_length=100)),
                ('review_status', models.CharField(choices=[('auto', 'Auto (high confidence)'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('orphaned', 'Orphaned (page changed)')], db_index=True, default='auto', max_length=10)),
                ('human_verified', models.BooleanField(default=False)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_extractions', to='search_engine.document')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'extraction_document_structures',
                'constraints': [models.UniqueConstraint(fields=('document', 'kind', 'extractor_name', 'extractor_version'), name='structure_unique_per_version')],
            },
        ),
        migrations.AddIndex(
            model_name='work',
            index=models.Index(fields=['-mention_doc_count'], name='extraction__mention_53a08b_idx'),
        ),
        migrations.AddIndex(
            model_name='entityrelation',
            index=models.Index(condition=models.Q(('superseded_at__isnull', True)), fields=['document', 'predicate'], name='relation_active_pred_idx'),
        ),
        migrations.AddConstraint(
            model_name='entityrelation',
            constraint=models.CheckConstraint(condition=models.Q(('char_end__gt', models.F('char_start'))), name='relation_span_valid'),
        ),
        migrations.AddConstraint(
            model_name='entityrelation',
            constraint=models.UniqueConstraint(fields=('document', 'extractor_name', 'extractor_version', 'dedupe_key'), name='relation_unique_per_version'),
        ),
        migrations.AlterUniqueTogether(
            name='workname',
            unique_together={('work', 'normalized', 'kind')},
        ),
    ]
