# Generated by Django 5.2.11 on 2026-02-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0006_create_category_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='authors_old',
            field=models.JSONField(blank=True, default=list, help_text='Legacy authors field (deprecated)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='categories_old',
            field=models.JSONField(blank=True, default=list, help_text='Legacy categories field (deprecated)'),
        ),
    ]
