# Generated by Django 5.2.11 on 2026-02-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0007_alter_document_authors_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='processing_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of processing attempts'),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_completed_at',
            field=models.DateTimeField(blank=True, help_text='When processing last completed (success/failure)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Last processing error (if any)', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, help_text='When processing was last started', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', help_text='State of asynchronous document processing', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='semantic_vector',
            field=models.JSONField(blank=True, default=list, help_text='Deterministic embedding vector used for hybrid search reranking'),
        ),
    ]
