# Generated by Django 5.2.11 on 2026-03-01

from django.db import migrations


def _normalize_names(value):
    if value is None:
        return []

    if isinstance(value, str):
        candidates = value.replace(';', ',').split(',')
    elif isinstance(value, (list, tuple, set)):
        candidates = value
    else:
        return []

    names = []
    seen = set()
    for raw_name in candidates:
        if raw_name is None:
            continue
        name = str(raw_name).strip()
        if not name:
            continue
        normalized = name.casefold()
        if normalized in seen:
            continue
        seen.add(normalized)
        names.append(name)
    return names


def migrate_legacy_author_category_data(apps, schema_editor):
    Document = apps.get_model('search_engine', 'Document')
    Author = apps.get_model('search_engine', 'Author')
    Category = apps.get_model('search_engine', 'Category')

    author_cache = {}
    category_cache = {}

    for document in Document.objects.all().iterator(chunk_size=500):
        author_names = _normalize_names(getattr(document, 'authors_old', None))
        if author_names:
            author_objects = []
            for author_name in author_names:
                author = author_cache.get(author_name)
                if author is None:
                    author, _ = Author.objects.get_or_create(
                        name=author_name,
                        defaults={'alternate_names': []},
                    )
                    author_cache[author_name] = author
                author_objects.append(author)
            if author_objects:
                document.authors.add(*author_objects)

        category_names = _normalize_names(getattr(document, 'categories_old', None))
        if category_names:
            category_objects = []
            for category_name in category_names:
                category = category_cache.get(category_name)
                if category is None:
                    category, _ = Category.objects.get_or_create(name=category_name)
                    category_cache[category_name] = category
                category_objects.append(category)
            if category_objects:
                document.categories.add(*category_objects)


def reverse_migrate_legacy_author_category_data(apps, schema_editor):
    Document = apps.get_model('search_engine', 'Document')

    for document in Document.objects.all().iterator(chunk_size=500):
        document.authors_old = list(document.authors.values_list('name', flat=True))
        document.categories_old = list(document.categories.values_list('name', flat=True))
        document.save(update_fields=['authors_old', 'categories_old'])


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0008_document_processing_fields'),
    ]

    operations = [
        migrations.RunPython(
            migrate_legacy_author_category_data,
            reverse_migrate_legacy_author_category_data,
        ),
        migrations.RemoveField(
            model_name='document',
            name='authors_old',
        ),
        migrations.RemoveField(
            model_name='document',
            name='categories_old',
        ),
    ]
