# Generated by Django 5.2.13 on 2026-04-17 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0011_document_ocr_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReaderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_size', models.CharField(default='medium', max_length=10)),
                ('theme', models.CharField(default='light', max_length=10)),
                ('font_weight', models.PositiveSmallIntegerField(default=400)),
                ('letter_spacing', models.FloatField(default=0.0)),
                ('line_height', models.FloatField(default=1.8)),
                ('tashkeel_enabled', models.BooleanField(default=True)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reader_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reader Preference',
                'verbose_name_plural': 'Reader Preferences',
                'db_table': 'search_engine_reader_preferences',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('paragraph_id', models.CharField(blank=True, default='', max_length=64)),
                ('label', models.CharField(blank=True, default='', max_length=200)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='search_engine.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'db_table': 'search_engine_bookmarks',
                'ordering': ['document', 'page_number'],
                'indexes': [models.Index(fields=['user', 'document'], name='search_engi_user_id_98cf8c_idx')],
                'unique_together': {('user', 'document', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('paragraph_id', models.CharField(max_length=64)),
                ('char_start', models.PositiveIntegerField()),
                ('char_end', models.PositiveIntegerField()),
                ('color', models.CharField(choices=[('yellow', 'yellow'), ('green', 'green'), ('blue', 'blue'), ('pink', 'pink'), ('orange', 'orange')], default='yellow', max_length=10)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to='search_engine.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Highlight',
                'verbose_name_plural': 'Highlights',
                'db_table': 'search_engine_highlights',
                'ordering': ['document', 'page_number', 'char_start'],
                'indexes': [models.Index(fields=['user', 'document'], name='search_engi_user_id_e1cfee_idx'), models.Index(fields=['document', 'page_number'], name='search_engi_documen_685aa0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('paragraph_id', models.CharField(blank=True, default='', max_length=64)),
                ('body', models.TextField()),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='search_engine.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
                'db_table': 'search_engine_notes',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'document'], name='search_engi_user_id_cffd80_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_page', models.PositiveIntegerField(default=1)),
                ('last_paragraph_id', models.CharField(blank=True, default='', max_length=64)),
                ('scroll_ratio', models.FloatField(default=0.0)),
                ('percent_complete', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='search_engine.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reading Progress',
                'verbose_name_plural': 'Reading Progress',
                'db_table': 'search_engine_reading_progress',
                'indexes': [models.Index(fields=['user', '-updated_at'], name='search_engi_user_id_12cb5c_idx')],
                'unique_together': {('user', 'document')},
            },
        ),
    ]
