# Generated by Django 5.2.14 on 2026-05-22 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0013_docling_engine_and_structured_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('order', models.PositiveIntegerField(default=0)),
                ('page_start', models.PositiveIntegerField()),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='search_engine.document')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='search_engine.chapter')),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'db_table': 'search_engine_chapters',
                'ordering': ['document', 'order'],
                'indexes': [models.Index(fields=['document', 'order'], name='search_engi_documen_4e87f8_idx')],
            },
        ),
    ]
