# Generated by Django 5.2.14 on 2026-06-07 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0015_chatsession_chatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='nationality',
            field=models.CharField(blank=True, help_text='Nationality of the author', max_length=100, null=True),
        ),
    ]
