# Generated by Django 5.2.14 on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0016_author_nationality'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDocumentCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(db_index=True, help_text='Country name (normalised to match Author.nationality)', max_length=100, unique=True)),
                ('document_count', models.PositiveIntegerField(default=0, help_text='Number of distinct documents whose authors belong to this country')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country Document Count',
                'verbose_name_plural': 'Country Document Counts',
                'db_table': 'search_engine_country_document_counts',
                'ordering': ['-document_count', 'country'],
            },
        ),
    ]
