# Generated by Django 5.2.14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0016_document_word_count_page_count'),
        ('search_engine', '0017_countrydocumentcount'),
    ]

    operations = [
    ]
