# Generated by Django 5.2.15 on 2026-07-01 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0018_merge_0017_countrydocumentcount_0016_document_word_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='context_scope',
            field=models.CharField(choices=[('auto', 'auto'), ('page', 'page'), ('book', 'book')], default='auto', max_length=8),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pinned_context',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
