# Generated by Django 5.2.15 on 2026-07-01 02:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0019_chatsession_context_scope_chatsession_pinned_context_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('paragraph_id', models.CharField(blank=True, default='', max_length=64)),
                ('char_start', models.PositiveIntegerField()),
                ('char_end', models.PositiveIntegerField()),
                ('selected_text', models.TextField()),
                ('description', models.TextField()),
                ('suggested_correction', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_corrections', to='search_engine.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Text Correction',
                'verbose_name_plural': 'Text Corrections',
                'db_table': 'search_engine_text_corrections',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'document'], name='search_engi_user_id_717594_idx'), models.Index(fields=['document', 'page_number'], name='search_engi_documen_dbdf65_idx')],
            },
        ),
    ]
