# Generated by Django 5.2.15 on 2026-07-01 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0020_textcorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFilterPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_filter_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Filter Preference',
                'verbose_name_plural': 'Document Filter Preferences',
                'db_table': 'search_engine_document_filter_preference',
            },
        ),
        migrations.CreateModel(
            name='SavedFilterPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_filter_presets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Filter Preset',
                'verbose_name_plural': 'Saved Filter Presets',
                'db_table': 'search_engine_saved_filter_preset',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
