# Generated by Django 5.2.15 on 2026-07-01 04:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0021_documentfilterpreference_savedfilterpreset'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Library Chat Session',
                'verbose_name_plural': 'Library Chat Sessions',
                'db_table': 'search_engine_library_chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LibraryChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=64)),
                ('role', models.CharField(choices=[('user', 'user'), ('assistant', 'assistant')], max_length=12)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='search_engine.librarychatsession')),
            ],
            options={
                'verbose_name': 'Library Chat Message',
                'verbose_name_plural': 'Library Chat Messages',
                'db_table': 'search_engine_library_chat_messages',
                'ordering': ['session', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='librarychatsession',
            index=models.Index(fields=['user', '-updated_at'], name='search_engi_user_id_6aee12_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='librarychatsession',
            unique_together={('user', 'thread_id')},
        ),
        migrations.AddIndex(
            model_name='librarychatmessage',
            index=models.Index(fields=['session', 'created_at'], name='search_engi_session_d17700_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='librarychatmessage',
            unique_together={('session', 'client_id')},
        ),
    ]
