# Generated by Django 5.2.15 on 2026-07-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0022_librarychatsession_librarychatmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='has_layout',
            field=models.BooleanField(default=False, help_text='True when this document was ingested with an OCR layout JSON (PDF-overlay reader mode)'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_layout',
            field=models.FileField(blank=True, help_text='Optional datalab/marker OCR JSON with per-block bounding boxes; when present the reader renders the original PDF page image with a transparent text overlay', null=True, upload_to='documents/ocr/'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='layout',
            field=models.JSONField(blank=True, help_text='Per-page OCR geometry {width, height, blocks:[{id, type, bbox, text, char_start, char_end}]} used to position the transparent text overlay', null=True),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='page_image',
            field=models.ImageField(blank=True, help_text='Rendered image of this PDF page shown beneath the transparent text overlay', null=True, upload_to='documents/pages/'),
        ),
    ]
