# Generated by Django 5.2.15 on 2026-07-03 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0023_document_has_layout_document_ocr_layout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='provenance_source',
            field=models.CharField(blank=True, default='', help_text="Where the digital text came from (e.g. 'scan of Dar X 1407H edition', 'Shamela import')", max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='rights_notes',
            field=models.TextField(blank=True, default='', help_text='Free-form notes supporting the rights classification'),
        ),
        migrations.AddField(
            model_name='document',
            name='rights_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('clear', 'Clear'), ('gray', 'Gray area'), ('restricted', 'Restricted')], db_index=True, default='unreviewed', help_text='Rights-audit classification: the base heritage text is public domain, but modern critical apparatus (tahqiq, footnotes, introductions) may carry editor/publisher rights', max_length=20),
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.CharField(blank=True, default='', help_text='Editor / muhaqqiq (المحقق) of this printed edition', max_length=255)),
                ('publisher', models.CharField(blank=True, default='', help_text='Publishing house (دار النشر)', max_length=255)),
                ('publication_place', models.CharField(blank=True, default='', help_text='Place of publication', max_length=255)),
                ('edition_statement', models.CharField(blank=True, default='', help_text="Edition statement, e.g. 'الطبعة الثانية'", max_length=100)),
                ('publication_year_hijri', models.CharField(blank=True, default='', help_text="Hijri publication year (flexible format, e.g. '1407' or '1407–1410هـ')", max_length=50)),
                ('publication_year_gregorian', models.CharField(blank=True, default='', help_text='Gregorian publication year (flexible format)', max_length=50)),
                ('volume_count', models.PositiveIntegerField(blank=True, null=True)),
                ('page_map', models.JSONField(blank=True, default=list, help_text='Digital→printed page ranges, e.g. [{"volume": 2, "from_page": 120, "to_page": 250, "printed_start": 1}]. Page numbers are the DIGITAL page numbers of this document; reprocessing a non-layout document with a different OCR engine can renumber pages and silently invalidate this map (PDF-overlay documents are safe).')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='search_engine.document')),
            ],
            options={
                'verbose_name': 'Edition',
                'verbose_name_plural': 'Editions',
                'db_table': 'search_engine_editions',
                'ordering': ['document', 'id'],
            },
        ),
    ]
