# Generated by Django 5.2.15 on 2026-07-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0024_document_provenance_source_document_rights_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='citations',
            field=models.JSONField(blank=True, default=list, help_text="Assistant citations: [{page: int, quote: str, volume?: int, printed_page?: int}, ...]; volume/printed_page are derived from the document's Edition page_map when mapped"),
        ),
    ]
