# Generated by Django 5.2.15 on 2026-07-12 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0025_alter_chatmessage_citations'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='death_century',
            field=models.IntegerField(blank=True, db_index=True, help_text='Derived hijri century of death (year 728 -> 8); null when unknown', null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death_year_hijri',
            field=models.IntegerField(blank=True, help_text='Derived hijri death year parsed from date_of_death; null when unparseable', null=True),
        ),
    ]
