# Generated by Django 5.2.16 on 2026-07-25 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0027_backfill_author_death_years'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text="User who uploaded the document; NULL for legacy uploads that predate ownership tracking (the 'my uploads' search scope only covers attributed documents)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
